backend:
  name: git-gateway
  branch: main

media_folder: "assets"
public_folder: "assets"

collections:
  - name: "imoveis"
    label: "Imóveis"
    folder: "imoveis"
    create: true
    delete: true
    slug: "{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Preço", name: "price", widget: "string"}
      - {label: "Localização", name: "location", widget: "string"}
      - label: "Galeria de Fotos"
        name: "photos"
        widget: "list"
        summary: '{{fields.photo}}'
        field: {label: "Foto", name: "photo", widget: "image"}
      - {label: "Descrição", name: "body", widget: "markdown"}
