backend:
  name: git-gateway
  branch: main

media_folder: "assets"
public_folder: "assets"

collections:
  - name: "imoveis"
    label: "Imóveis"
    folder: "imoveis"
    create: true
    delete: true # Permite excluir anúncios pelo painel
    slug: "{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Preço", name: "price", widget: "string"}
      - {label: "Localização", name: "location", widget: "string"}
      - {label: "Foto principal", name: "image", widget: "image", required: false}
      - {label: "Descrição", name: "body", widget: "markdown"}
